name: mcfcc_nsn
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/mw205/mfcc_nsn

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  fft_nullsafety: ^0.2.1
  js_interop: ^0.0.1
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
